Using array [2 3 5 6 1 2 4] write Numpy program to:  

Get a new array with elements greater than 3 

In [2]:
import numpy as np 

a = np.array([2,3,5,6,1,2,4])
print(f"The original numpy array {a}")

b = a[a> 3]
print(f"The elements greater than 3:{b}")

The original numpy array [2 3 5 6 1 2 4]
The elements greater than 3:[5 6 4]


Get a new array with squared elements 

In [3]:
squared_elements = a ** 2
print(f"array with squared elements:{squared_elements}")

array with squared elements:[ 4  9 25 36  1  4 16]


Get a new array with elements greater than average value 

In [4]:
average_value = np.mean(a)
print(f"average value: {average_value}")
b =a[average_value < a]
print(f"array with elements greater than average value: {b}")


average value: 3.2857142857142856
array with elements greater than average value: [5 6 4]


Create an element-wise multiplication/division/addition of two given arrays (second array- [1 2 1 2 1 2 3]) 

In [5]:
b = np.array([1,2,1,2,1,2,3])
print(f"First array {a}")
print(f"Second array {b}")

multiplication = np.multiply(a,b)
print(f"Multiplication of two given arrays:{multiplication}")

divison = np.divide(a,b)
print(f"Divison of two given arrays:{divison}")

addition = np.add(a,b)
print(f"Addition of two given arrays:{addition}")

subtract = np.subtract(a,b)
print(f"Subtract of two given arrays:{subtract}")

First array [2 3 5 6 1 2 4]
Second array [1 2 1 2 1 2 3]
Multiplication of two given arrays:[ 2  6  5 12  1  4 12]
Divison of two given arrays:[2.         1.5        5.         3.         1.         1.
 1.33333333]
Addition of two given arrays:[3 5 6 8 2 4 7]
Subtract of two given arrays:[1 1 4 4 0 0 1]


In [7]:
np.divide(b,a) 

array([0.5       , 0.66666667, 0.2       , 0.33333333, 1.        ,
       1.        , 0.75      ])

In [8]:
np.add(b,a) 

array([3, 5, 6, 8, 2, 4, 7])

In [9]:
np.multiply(b,a)

array([ 2,  6,  5, 12,  1,  4, 12])

In [10]:
np.subtract(b,a)

array([-1, -1, -4, -4,  0,  0, -1])

In [11]:
np.floor_divide(b,a)

array([0, 0, 0, 0, 1, 1, 0])